name: Build APK (React Native)

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Decode keystore from base64
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/release.keystore

      - name: Create gradle.properties
        run: |
          cat >> android/gradle.properties <<EOF
          MYAPP_RELEASE_STORE_FILE=release.keystore
          MYAPP_RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MYAPP_RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          MYAPP_RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Install dependencies
        run: |
          yarn install

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Cache NodeModules
        use: actions/cache@v3
        with:
          path: |
            node_modules
            ${{ github.workspace }}/android/.gradle
            ~/.gradle
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Firebase Cli
        run: |
          yarn global add firebase-tools

      - name: Decode Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" | base64 -d > firebase.json
      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app 1:363019288417:android:5497f197fb0c8c5901cf20 \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --release-notes "New build from GitHub Actions" \
            --groups "Tester"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase.json
